# Generated by Django 3.2.6 on 2021-08-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=300)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/')),
            ],
        ),
    ]
